version: '{build}'
os: Visual Studio 2015

configuration:
- Release

install:
- choco install -y InnoSetup
- choco install nasm

before_build:
- cmake -H. -Bvs2013-x64 -G"Visual Studio 12 2013 Win64"
- cmake -H. -Bvs2013-x86 -G"Visual Studio 12 2013"
- cmake -H. -Bvs2015-x64 -G"Visual Studio 14 2015 Win64"
- cmake -H. -Bvs2015-x86 -G"Visual Studio 14 2015"



build_script:
- cmake --build vs2013-x64 --config Release --target installer
- cmake --build vs2013-x86 --config Release --target installer
- cmake --build vs2015-x64 --config Release --target installer
- cmake --build vs2015-x86 --config Release --target installer

artifacts:
  - path: LuaVM*.exe

deploy:
- provider: GitHub
  description: Release of v$(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: 9u2iMRO2KmnGYYLq9tqm0su2eY3h9FprKV8600vkNsFVCcM0ukfaZuu6SDGb95a6
  artifact: /LuaVM.+\.exe/
  draft: false
  prerelease: true
  on:
    appveyor_repo_tag: true
- provider: BinTray
  username: xpol
  api_key:
    secure: b+4yTLIkX5eZxGWyK4gW6atxDSje5+wFa7PwOoMB162Ulvo3TndrmTH2jYGUwzqA
  subject: xpol
  repo: luavm
  package: luavm-development
  version: v$(APPVEYOR_REPO_TAG_NAME)
  publish: true
  override: true
  explode: true
  on:
    appveyor_repo_tag: true
