name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2016]
        
    steps:
#    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        where /r "C:\Program Files (x86)\Microsoft Visual Studio" *.bat
